name: ezviz_flutter
description: A comprehensive Flutter/Dart library for EZVIZ camera API integration featuring EzvizSimplePlayer for easy camera integration, device management, live streaming, PTZ control, and more.
version: 1.2.4
homepage: https://github.com/akshaynexus/ezviz_flutter
repository: https://github.com/akshaynexus/ezviz_flutter

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  meta: ^1.9.1
  plugin_platform_interface: ^2.0.2
  # path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^5.0.0
  test: ^1.24.0
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

# Flutter plugin configuration for native SDK integration
flutter:
  plugin:
    platforms:
      android:
        package: com.akshaynexus.ezviz_flutter.ezviz_flutter
        pluginClass: FlutterEzvizPlugin
      ios:
        pluginClass: FlutterEzvizPlugin
